//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SATEntities : DbContext
    {
        public SATEntities()
            : base("name=SATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAlumnos> tbAlumnos { get; set; }
        public virtual DbSet<tbMatriculas> tbMatriculas { get; set; }
        public virtual DbSet<tbNotaDetalles> tbNotaDetalles { get; set; }
        public virtual DbSet<tbNotas> tbNotas { get; set; }
        public virtual DbSet<tbAsignaturas> tbAsignaturas { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCarreraAsignaturas> tbCarreraAsignaturas { get; set; }
        public virtual DbSet<tbCarreras> tbCarreras { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleadoAsignaturas> tbEmpleadoAsignaturas { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEscuelas> tbEscuelas { get; set; }
        public virtual DbSet<tbGrados> tbGrados { get; set; }
        public virtual DbSet<tbJornadaGrados> tbJornadaGrados { get; set; }
        public virtual DbSet<tbJornadas> tbJornadas { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbSecciones> tbSecciones { get; set; }
    
        public virtual ObjectResult<string> UDP_Acce_tbUsuario_Insert(string usu_NombreUsuario, string usu_Password, Nullable<bool> usu_EsAdministrador)
        {
            var usu_NombreUsuarioParameter = usu_NombreUsuario != null ?
                new ObjectParameter("usu_NombreUsuario", usu_NombreUsuario) :
                new ObjectParameter("usu_NombreUsuario", typeof(string));
    
            var usu_PasswordParameter = usu_Password != null ?
                new ObjectParameter("usu_Password", usu_Password) :
                new ObjectParameter("usu_Password", typeof(string));
    
            var usu_EsAdministradorParameter = usu_EsAdministrador.HasValue ?
                new ObjectParameter("usu_EsAdministrador", usu_EsAdministrador) :
                new ObjectParameter("usu_EsAdministrador", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Acce_tbUsuario_Insert", usu_NombreUsuarioParameter, usu_PasswordParameter, usu_EsAdministradorParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> UDP_Esc_tbNotaDetalles_Insert(Nullable<int> not_Id, Nullable<decimal> notd_Acumulado1, Nullable<decimal> notd_Examen1, Nullable<decimal> notd_Acumulado2, Nullable<decimal> notd_Examen2, Nullable<decimal> notd_Acumulado3, Nullable<decimal> notd_Examen3, Nullable<decimal> notd_Acumulado4, Nullable<decimal> notd_Examen4, Nullable<int> notd_UsuarioCrea, Nullable<System.DateTime> notd_FechaCrea)
        {
            var not_IdParameter = not_Id.HasValue ?
                new ObjectParameter("not_Id", not_Id) :
                new ObjectParameter("not_Id", typeof(int));
    
            var notd_Acumulado1Parameter = notd_Acumulado1.HasValue ?
                new ObjectParameter("notd_Acumulado1", notd_Acumulado1) :
                new ObjectParameter("notd_Acumulado1", typeof(decimal));
    
            var notd_Examen1Parameter = notd_Examen1.HasValue ?
                new ObjectParameter("notd_Examen1", notd_Examen1) :
                new ObjectParameter("notd_Examen1", typeof(decimal));
    
            var notd_Acumulado2Parameter = notd_Acumulado2.HasValue ?
                new ObjectParameter("notd_Acumulado2", notd_Acumulado2) :
                new ObjectParameter("notd_Acumulado2", typeof(decimal));
    
            var notd_Examen2Parameter = notd_Examen2.HasValue ?
                new ObjectParameter("notd_Examen2", notd_Examen2) :
                new ObjectParameter("notd_Examen2", typeof(decimal));
    
            var notd_Acumulado3Parameter = notd_Acumulado3.HasValue ?
                new ObjectParameter("notd_Acumulado3", notd_Acumulado3) :
                new ObjectParameter("notd_Acumulado3", typeof(decimal));
    
            var notd_Examen3Parameter = notd_Examen3.HasValue ?
                new ObjectParameter("notd_Examen3", notd_Examen3) :
                new ObjectParameter("notd_Examen3", typeof(decimal));
    
            var notd_Acumulado4Parameter = notd_Acumulado4.HasValue ?
                new ObjectParameter("notd_Acumulado4", notd_Acumulado4) :
                new ObjectParameter("notd_Acumulado4", typeof(decimal));
    
            var notd_Examen4Parameter = notd_Examen4.HasValue ?
                new ObjectParameter("notd_Examen4", notd_Examen4) :
                new ObjectParameter("notd_Examen4", typeof(decimal));
    
            var notd_UsuarioCreaParameter = notd_UsuarioCrea.HasValue ?
                new ObjectParameter("notd_UsuarioCrea", notd_UsuarioCrea) :
                new ObjectParameter("notd_UsuarioCrea", typeof(int));
    
            var notd_FechaCreaParameter = notd_FechaCrea.HasValue ?
                new ObjectParameter("notd_FechaCrea", notd_FechaCrea) :
                new ObjectParameter("notd_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Esc_tbNotaDetalles_Insert", not_IdParameter, notd_Acumulado1Parameter, notd_Examen1Parameter, notd_Acumulado2Parameter, notd_Examen2Parameter, notd_Acumulado3Parameter, notd_Examen3Parameter, notd_Acumulado4Parameter, notd_Examen4Parameter, notd_UsuarioCreaParameter, notd_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Esc_tbNotaDetalles_Update(Nullable<int> notd_Id, Nullable<int> not_Id, Nullable<decimal> notd_Examen1, Nullable<decimal> notd_Examen2, Nullable<decimal> notd_Examen3, Nullable<decimal> notd_Examen4, Nullable<decimal> notd_Acumulado1, Nullable<decimal> notd_Acumulado2, Nullable<decimal> notd_Acumulado3, Nullable<decimal> notd_Acumulado4, Nullable<int> notd_UsuarioCrea, Nullable<System.DateTime> notd_FechaCrea, Nullable<int> notd_UsuarioModifica, Nullable<System.DateTime> notd_FechaModifica)
        {
            var notd_IdParameter = notd_Id.HasValue ?
                new ObjectParameter("notd_Id", notd_Id) :
                new ObjectParameter("notd_Id", typeof(int));
    
            var not_IdParameter = not_Id.HasValue ?
                new ObjectParameter("not_Id", not_Id) :
                new ObjectParameter("not_Id", typeof(int));
    
            var notd_Examen1Parameter = notd_Examen1.HasValue ?
                new ObjectParameter("notd_Examen1", notd_Examen1) :
                new ObjectParameter("notd_Examen1", typeof(decimal));
    
            var notd_Examen2Parameter = notd_Examen2.HasValue ?
                new ObjectParameter("notd_Examen2", notd_Examen2) :
                new ObjectParameter("notd_Examen2", typeof(decimal));
    
            var notd_Examen3Parameter = notd_Examen3.HasValue ?
                new ObjectParameter("notd_Examen3", notd_Examen3) :
                new ObjectParameter("notd_Examen3", typeof(decimal));
    
            var notd_Examen4Parameter = notd_Examen4.HasValue ?
                new ObjectParameter("notd_Examen4", notd_Examen4) :
                new ObjectParameter("notd_Examen4", typeof(decimal));
    
            var notd_Acumulado1Parameter = notd_Acumulado1.HasValue ?
                new ObjectParameter("notd_Acumulado1", notd_Acumulado1) :
                new ObjectParameter("notd_Acumulado1", typeof(decimal));
    
            var notd_Acumulado2Parameter = notd_Acumulado2.HasValue ?
                new ObjectParameter("notd_Acumulado2", notd_Acumulado2) :
                new ObjectParameter("notd_Acumulado2", typeof(decimal));
    
            var notd_Acumulado3Parameter = notd_Acumulado3.HasValue ?
                new ObjectParameter("notd_Acumulado3", notd_Acumulado3) :
                new ObjectParameter("notd_Acumulado3", typeof(decimal));
    
            var notd_Acumulado4Parameter = notd_Acumulado4.HasValue ?
                new ObjectParameter("notd_Acumulado4", notd_Acumulado4) :
                new ObjectParameter("notd_Acumulado4", typeof(decimal));
    
            var notd_UsuarioCreaParameter = notd_UsuarioCrea.HasValue ?
                new ObjectParameter("notd_UsuarioCrea", notd_UsuarioCrea) :
                new ObjectParameter("notd_UsuarioCrea", typeof(int));
    
            var notd_FechaCreaParameter = notd_FechaCrea.HasValue ?
                new ObjectParameter("notd_FechaCrea", notd_FechaCrea) :
                new ObjectParameter("notd_FechaCrea", typeof(System.DateTime));
    
            var notd_UsuarioModificaParameter = notd_UsuarioModifica.HasValue ?
                new ObjectParameter("notd_UsuarioModifica", notd_UsuarioModifica) :
                new ObjectParameter("notd_UsuarioModifica", typeof(int));
    
            var notd_FechaModificaParameter = notd_FechaModifica.HasValue ?
                new ObjectParameter("notd_FechaModifica", notd_FechaModifica) :
                new ObjectParameter("notd_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Esc_tbNotaDetalles_Update", notd_IdParameter, not_IdParameter, notd_Examen1Parameter, notd_Examen2Parameter, notd_Examen3Parameter, notd_Examen4Parameter, notd_Acumulado1Parameter, notd_Acumulado2Parameter, notd_Acumulado3Parameter, notd_Acumulado4Parameter, notd_UsuarioCreaParameter, notd_FechaCreaParameter, notd_UsuarioModificaParameter, notd_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Esc_tbNotas_Insert(Nullable<int> asig_Id, Nullable<int> mat_Id, Nullable<int> not_UsuarioCrea, Nullable<System.DateTime> not_FechaCrea)
        {
            var asig_IdParameter = asig_Id.HasValue ?
                new ObjectParameter("asig_Id", asig_Id) :
                new ObjectParameter("asig_Id", typeof(int));
    
            var mat_IdParameter = mat_Id.HasValue ?
                new ObjectParameter("mat_Id", mat_Id) :
                new ObjectParameter("mat_Id", typeof(int));
    
            var not_UsuarioCreaParameter = not_UsuarioCrea.HasValue ?
                new ObjectParameter("not_UsuarioCrea", not_UsuarioCrea) :
                new ObjectParameter("not_UsuarioCrea", typeof(int));
    
            var not_FechaCreaParameter = not_FechaCrea.HasValue ?
                new ObjectParameter("not_FechaCrea", not_FechaCrea) :
                new ObjectParameter("not_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Esc_tbNotas_Insert", asig_IdParameter, mat_IdParameter, not_UsuarioCreaParameter, not_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Esc_tbNotas_Update(Nullable<int> not_Id, Nullable<int> asig_Id, Nullable<int> mat_Id, Nullable<int> not_UsuarioCrea, Nullable<System.DateTime> not_FechaCrea, Nullable<int> not_UsuarioModifica, Nullable<System.DateTime> not_FechaModifica)
        {
            var not_IdParameter = not_Id.HasValue ?
                new ObjectParameter("not_Id", not_Id) :
                new ObjectParameter("not_Id", typeof(int));
    
            var asig_IdParameter = asig_Id.HasValue ?
                new ObjectParameter("asig_Id", asig_Id) :
                new ObjectParameter("asig_Id", typeof(int));
    
            var mat_IdParameter = mat_Id.HasValue ?
                new ObjectParameter("mat_Id", mat_Id) :
                new ObjectParameter("mat_Id", typeof(int));
    
            var not_UsuarioCreaParameter = not_UsuarioCrea.HasValue ?
                new ObjectParameter("not_UsuarioCrea", not_UsuarioCrea) :
                new ObjectParameter("not_UsuarioCrea", typeof(int));
    
            var not_FechaCreaParameter = not_FechaCrea.HasValue ?
                new ObjectParameter("not_FechaCrea", not_FechaCrea) :
                new ObjectParameter("not_FechaCrea", typeof(System.DateTime));
    
            var not_UsuarioModificaParameter = not_UsuarioModifica.HasValue ?
                new ObjectParameter("not_UsuarioModifica", not_UsuarioModifica) :
                new ObjectParameter("not_UsuarioModifica", typeof(int));
    
            var not_FechaModificaParameter = not_FechaModifica.HasValue ?
                new ObjectParameter("not_FechaModifica", not_FechaModifica) :
                new ObjectParameter("not_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Esc_tbNotas_Update", not_IdParameter, asig_IdParameter, mat_IdParameter, not_UsuarioCreaParameter, not_FechaCreaParameter, not_UsuarioModificaParameter, not_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbMatriculas_Insert(Nullable<int> alu_Id, Nullable<int> sec_Id, Nullable<int> car_Id, Nullable<int> mat_Anio, Nullable<int> mat_UsuarioCrea, Nullable<System.DateTime> mat_FechaCrea)
        {
            var alu_IdParameter = alu_Id.HasValue ?
                new ObjectParameter("alu_Id", alu_Id) :
                new ObjectParameter("alu_Id", typeof(int));
    
            var sec_IdParameter = sec_Id.HasValue ?
                new ObjectParameter("sec_Id", sec_Id) :
                new ObjectParameter("sec_Id", typeof(int));
    
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(int));
    
            var mat_AnioParameter = mat_Anio.HasValue ?
                new ObjectParameter("mat_Anio", mat_Anio) :
                new ObjectParameter("mat_Anio", typeof(int));
    
            var mat_UsuarioCreaParameter = mat_UsuarioCrea.HasValue ?
                new ObjectParameter("mat_UsuarioCrea", mat_UsuarioCrea) :
                new ObjectParameter("mat_UsuarioCrea", typeof(int));
    
            var mat_FechaCreaParameter = mat_FechaCrea.HasValue ?
                new ObjectParameter("mat_FechaCrea", mat_FechaCrea) :
                new ObjectParameter("mat_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbMatriculas_Insert", alu_IdParameter, sec_IdParameter, car_IdParameter, mat_AnioParameter, mat_UsuarioCreaParameter, mat_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbMatriculas_Update(Nullable<int> mat_Id, Nullable<int> alu_Id, Nullable<int> sec_Id, Nullable<int> car_Id, Nullable<int> mat_Anio, Nullable<int> mat_UsuarioCrea, Nullable<System.DateTime> mat_FechaCrea, Nullable<int> mat_UsuarioModifica, Nullable<System.DateTime> mat_FechaModifica)
        {
            var mat_IdParameter = mat_Id.HasValue ?
                new ObjectParameter("mat_Id", mat_Id) :
                new ObjectParameter("mat_Id", typeof(int));
    
            var alu_IdParameter = alu_Id.HasValue ?
                new ObjectParameter("alu_Id", alu_Id) :
                new ObjectParameter("alu_Id", typeof(int));
    
            var sec_IdParameter = sec_Id.HasValue ?
                new ObjectParameter("sec_Id", sec_Id) :
                new ObjectParameter("sec_Id", typeof(int));
    
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(int));
    
            var mat_AnioParameter = mat_Anio.HasValue ?
                new ObjectParameter("mat_Anio", mat_Anio) :
                new ObjectParameter("mat_Anio", typeof(int));
    
            var mat_UsuarioCreaParameter = mat_UsuarioCrea.HasValue ?
                new ObjectParameter("mat_UsuarioCrea", mat_UsuarioCrea) :
                new ObjectParameter("mat_UsuarioCrea", typeof(int));
    
            var mat_FechaCreaParameter = mat_FechaCrea.HasValue ?
                new ObjectParameter("mat_FechaCrea", mat_FechaCrea) :
                new ObjectParameter("mat_FechaCrea", typeof(System.DateTime));
    
            var mat_UsuarioModificaParameter = mat_UsuarioModifica.HasValue ?
                new ObjectParameter("mat_UsuarioModifica", mat_UsuarioModifica) :
                new ObjectParameter("mat_UsuarioModifica", typeof(int));
    
            var mat_FechaModificaParameter = mat_FechaModifica.HasValue ?
                new ObjectParameter("mat_FechaModifica", mat_FechaModifica) :
                new ObjectParameter("mat_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbMatriculas_Update", mat_IdParameter, alu_IdParameter, sec_IdParameter, car_IdParameter, mat_AnioParameter, mat_UsuarioCreaParameter, mat_FechaCreaParameter, mat_UsuarioModificaParameter, mat_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbAsignaturas_Insert(string asig_Descripcion, Nullable<bool> asig_Semestral, Nullable<int> asig_UsuarioCrea, Nullable<System.DateTime> asig_FechaCrea)
        {
            var asig_DescripcionParameter = asig_Descripcion != null ?
                new ObjectParameter("asig_Descripcion", asig_Descripcion) :
                new ObjectParameter("asig_Descripcion", typeof(string));
    
            var asig_SemestralParameter = asig_Semestral.HasValue ?
                new ObjectParameter("asig_Semestral", asig_Semestral) :
                new ObjectParameter("asig_Semestral", typeof(bool));
    
            var asig_UsuarioCreaParameter = asig_UsuarioCrea.HasValue ?
                new ObjectParameter("asig_UsuarioCrea", asig_UsuarioCrea) :
                new ObjectParameter("asig_UsuarioCrea", typeof(int));
    
            var asig_FechaCreaParameter = asig_FechaCrea.HasValue ?
                new ObjectParameter("asig_FechaCrea", asig_FechaCrea) :
                new ObjectParameter("asig_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbAsignaturas_Insert", asig_DescripcionParameter, asig_SemestralParameter, asig_UsuarioCreaParameter, asig_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbAsignaturas_Update(Nullable<int> asig_Id, string asig_Descripcion, Nullable<bool> asig_Semestral, Nullable<int> asig_UsuarioCrea, Nullable<System.DateTime> asig_FechaCrea, Nullable<int> asig_UsuarioModifica, Nullable<System.DateTime> asig_FechaModifica)
        {
            var asig_IdParameter = asig_Id.HasValue ?
                new ObjectParameter("asig_Id", asig_Id) :
                new ObjectParameter("asig_Id", typeof(int));
    
            var asig_DescripcionParameter = asig_Descripcion != null ?
                new ObjectParameter("asig_Descripcion", asig_Descripcion) :
                new ObjectParameter("asig_Descripcion", typeof(string));
    
            var asig_SemestralParameter = asig_Semestral.HasValue ?
                new ObjectParameter("asig_Semestral", asig_Semestral) :
                new ObjectParameter("asig_Semestral", typeof(bool));
    
            var asig_UsuarioCreaParameter = asig_UsuarioCrea.HasValue ?
                new ObjectParameter("asig_UsuarioCrea", asig_UsuarioCrea) :
                new ObjectParameter("asig_UsuarioCrea", typeof(int));
    
            var asig_FechaCreaParameter = asig_FechaCrea.HasValue ?
                new ObjectParameter("asig_FechaCrea", asig_FechaCrea) :
                new ObjectParameter("asig_FechaCrea", typeof(System.DateTime));
    
            var asig_UsuarioModificaParameter = asig_UsuarioModifica.HasValue ?
                new ObjectParameter("asig_UsuarioModifica", asig_UsuarioModifica) :
                new ObjectParameter("asig_UsuarioModifica", typeof(int));
    
            var asig_FechaModificaParameter = asig_FechaModifica.HasValue ?
                new ObjectParameter("asig_FechaModifica", asig_FechaModifica) :
                new ObjectParameter("asig_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbAsignaturas_Update", asig_IdParameter, asig_DescripcionParameter, asig_SemestralParameter, asig_UsuarioCreaParameter, asig_FechaCreaParameter, asig_UsuarioModificaParameter, asig_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbCargos_Insert_Result> UDP_Gral_tbCargos_Insert(string carg_Descripcion, Nullable<int> carg_UsuarioCrea, Nullable<System.DateTime> carg_FechaCrea)
        {
            var carg_DescripcionParameter = carg_Descripcion != null ?
                new ObjectParameter("carg_Descripcion", carg_Descripcion) :
                new ObjectParameter("carg_Descripcion", typeof(string));
    
            var carg_UsuarioCreaParameter = carg_UsuarioCrea.HasValue ?
                new ObjectParameter("carg_UsuarioCrea", carg_UsuarioCrea) :
                new ObjectParameter("carg_UsuarioCrea", typeof(int));
    
            var carg_FechaCreaParameter = carg_FechaCrea.HasValue ?
                new ObjectParameter("carg_FechaCrea", carg_FechaCrea) :
                new ObjectParameter("carg_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbCargos_Insert_Result>("UDP_Gral_tbCargos_Insert", carg_DescripcionParameter, carg_UsuarioCreaParameter, carg_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_Gral_tbCargos_Update_Result> UDP_Gral_tbCargos_Update(Nullable<int> carg_Id, string carg_Descripcion, Nullable<int> carg_UsuarioCrea, Nullable<System.DateTime> carg_FechaCrea, Nullable<int> carg_UsuarioModifica, Nullable<System.DateTime> carg_FechaModifica)
        {
            var carg_IdParameter = carg_Id.HasValue ?
                new ObjectParameter("carg_Id", carg_Id) :
                new ObjectParameter("carg_Id", typeof(int));
    
            var carg_DescripcionParameter = carg_Descripcion != null ?
                new ObjectParameter("carg_Descripcion", carg_Descripcion) :
                new ObjectParameter("carg_Descripcion", typeof(string));
    
            var carg_UsuarioCreaParameter = carg_UsuarioCrea.HasValue ?
                new ObjectParameter("carg_UsuarioCrea", carg_UsuarioCrea) :
                new ObjectParameter("carg_UsuarioCrea", typeof(int));
    
            var carg_FechaCreaParameter = carg_FechaCrea.HasValue ?
                new ObjectParameter("carg_FechaCrea", carg_FechaCrea) :
                new ObjectParameter("carg_FechaCrea", typeof(System.DateTime));
    
            var carg_UsuarioModificaParameter = carg_UsuarioModifica.HasValue ?
                new ObjectParameter("carg_UsuarioModifica", carg_UsuarioModifica) :
                new ObjectParameter("carg_UsuarioModifica", typeof(int));
    
            var carg_FechaModificaParameter = carg_FechaModifica.HasValue ?
                new ObjectParameter("carg_FechaModifica", carg_FechaModifica) :
                new ObjectParameter("carg_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Gral_tbCargos_Update_Result>("UDP_Gral_tbCargos_Update", carg_IdParameter, carg_DescripcionParameter, carg_UsuarioCreaParameter, carg_FechaCreaParameter, carg_UsuarioModificaParameter, carg_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbCarreras_Insert(string descripcion, Nullable<int> encargado, Nullable<int> car_UsuarioCrea, Nullable<System.DateTime> car_FechaCrea)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var encargadoParameter = encargado.HasValue ?
                new ObjectParameter("Encargado", encargado) :
                new ObjectParameter("Encargado", typeof(int));
    
            var car_UsuarioCreaParameter = car_UsuarioCrea.HasValue ?
                new ObjectParameter("car_UsuarioCrea", car_UsuarioCrea) :
                new ObjectParameter("car_UsuarioCrea", typeof(int));
    
            var car_FechaCreaParameter = car_FechaCrea.HasValue ?
                new ObjectParameter("car_FechaCrea", car_FechaCrea) :
                new ObjectParameter("car_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbCarreras_Insert", descripcionParameter, encargadoParameter, car_UsuarioCreaParameter, car_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbCarreras_Update(Nullable<int> car_Id, string descripcion, Nullable<int> encargado, Nullable<int> car_UsuarioCrea, Nullable<System.DateTime> car_FechaCrea, Nullable<int> car_UsuarioModifica, Nullable<System.DateTime> car_FechaModifica)
        {
            var car_IdParameter = car_Id.HasValue ?
                new ObjectParameter("car_Id", car_Id) :
                new ObjectParameter("car_Id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var encargadoParameter = encargado.HasValue ?
                new ObjectParameter("Encargado", encargado) :
                new ObjectParameter("Encargado", typeof(int));
    
            var car_UsuarioCreaParameter = car_UsuarioCrea.HasValue ?
                new ObjectParameter("car_UsuarioCrea", car_UsuarioCrea) :
                new ObjectParameter("car_UsuarioCrea", typeof(int));
    
            var car_FechaCreaParameter = car_FechaCrea.HasValue ?
                new ObjectParameter("car_FechaCrea", car_FechaCrea) :
                new ObjectParameter("car_FechaCrea", typeof(System.DateTime));
    
            var car_UsuarioModificaParameter = car_UsuarioModifica.HasValue ?
                new ObjectParameter("car_UsuarioModifica", car_UsuarioModifica) :
                new ObjectParameter("car_UsuarioModifica", typeof(int));
    
            var car_FechaModificaParameter = car_FechaModifica.HasValue ?
                new ObjectParameter("car_FechaModifica", car_FechaModifica) :
                new ObjectParameter("car_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbCarreras_Update", car_IdParameter, descripcionParameter, encargadoParameter, car_UsuarioCreaParameter, car_FechaCreaParameter, car_UsuarioModificaParameter, car_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbDepartamentos_Insert(string dep_Id, string dep_Descripcion, Nullable<int> usu_Id, Nullable<System.DateTime> usu_Fechacrea)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var dep_DescripcionParameter = dep_Descripcion != null ?
                new ObjectParameter("dep_Descripcion", dep_Descripcion) :
                new ObjectParameter("dep_Descripcion", typeof(string));
    
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_FechacreaParameter = usu_Fechacrea.HasValue ?
                new ObjectParameter("usu_Fechacrea", usu_Fechacrea) :
                new ObjectParameter("usu_Fechacrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbDepartamentos_Insert", dep_IdParameter, dep_DescripcionParameter, usu_IdParameter, usu_FechacreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbDepartamentos_Update(string dep_Id, string dep_Descripcion, Nullable<int> dep_UsuarioCrea, Nullable<System.DateTime> dep_FechaCrea, Nullable<int> dep_UsuarioModifica, Nullable<System.DateTime> dep_FechaModifica)
        {
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            var dep_DescripcionParameter = dep_Descripcion != null ?
                new ObjectParameter("dep_Descripcion", dep_Descripcion) :
                new ObjectParameter("dep_Descripcion", typeof(string));
    
            var dep_UsuarioCreaParameter = dep_UsuarioCrea.HasValue ?
                new ObjectParameter("dep_UsuarioCrea", dep_UsuarioCrea) :
                new ObjectParameter("dep_UsuarioCrea", typeof(int));
    
            var dep_FechaCreaParameter = dep_FechaCrea.HasValue ?
                new ObjectParameter("dep_FechaCrea", dep_FechaCrea) :
                new ObjectParameter("dep_FechaCrea", typeof(System.DateTime));
    
            var dep_UsuarioModificaParameter = dep_UsuarioModifica.HasValue ?
                new ObjectParameter("dep_UsuarioModifica", dep_UsuarioModifica) :
                new ObjectParameter("dep_UsuarioModifica", typeof(int));
    
            var dep_FechaModificaParameter = dep_FechaModifica.HasValue ?
                new ObjectParameter("dep_FechaModifica", dep_FechaModifica) :
                new ObjectParameter("dep_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbDepartamentos_Update", dep_IdParameter, dep_DescripcionParameter, dep_UsuarioCreaParameter, dep_FechaCreaParameter, dep_UsuarioModificaParameter, dep_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEmpleados_Insert(string emp_Identidad, string emp_Nombres, string emp_Apellidos, Nullable<System.DateTime> emp_FechaNacimiento, string emp_Sexo, string emp_Direccion, string mun_Id, string emp_CorreoElectronico, string emp_Telefono, Nullable<int> carg_Id, Nullable<System.DateTime> emp_FechaIngreso, Nullable<System.DateTime> emp_FechadeSalida, string emp_RazonSalida, Nullable<int> emp_UsuarioCrea, Nullable<System.DateTime> emp_FechaCrea)
        {
            var emp_IdentidadParameter = emp_Identidad != null ?
                new ObjectParameter("emp_Identidad", emp_Identidad) :
                new ObjectParameter("emp_Identidad", typeof(string));
    
            var emp_NombresParameter = emp_Nombres != null ?
                new ObjectParameter("emp_Nombres", emp_Nombres) :
                new ObjectParameter("emp_Nombres", typeof(string));
    
            var emp_ApellidosParameter = emp_Apellidos != null ?
                new ObjectParameter("emp_Apellidos", emp_Apellidos) :
                new ObjectParameter("emp_Apellidos", typeof(string));
    
            var emp_FechaNacimientoParameter = emp_FechaNacimiento.HasValue ?
                new ObjectParameter("emp_FechaNacimiento", emp_FechaNacimiento) :
                new ObjectParameter("emp_FechaNacimiento", typeof(System.DateTime));
    
            var emp_SexoParameter = emp_Sexo != null ?
                new ObjectParameter("emp_Sexo", emp_Sexo) :
                new ObjectParameter("emp_Sexo", typeof(string));
    
            var emp_DireccionParameter = emp_Direccion != null ?
                new ObjectParameter("emp_Direccion", emp_Direccion) :
                new ObjectParameter("emp_Direccion", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var emp_CorreoElectronicoParameter = emp_CorreoElectronico != null ?
                new ObjectParameter("emp_CorreoElectronico", emp_CorreoElectronico) :
                new ObjectParameter("emp_CorreoElectronico", typeof(string));
    
            var emp_TelefonoParameter = emp_Telefono != null ?
                new ObjectParameter("emp_Telefono", emp_Telefono) :
                new ObjectParameter("emp_Telefono", typeof(string));
    
            var carg_IdParameter = carg_Id.HasValue ?
                new ObjectParameter("carg_Id", carg_Id) :
                new ObjectParameter("carg_Id", typeof(int));
    
            var emp_FechaIngresoParameter = emp_FechaIngreso.HasValue ?
                new ObjectParameter("emp_FechaIngreso", emp_FechaIngreso) :
                new ObjectParameter("emp_FechaIngreso", typeof(System.DateTime));
    
            var emp_FechadeSalidaParameter = emp_FechadeSalida.HasValue ?
                new ObjectParameter("emp_FechadeSalida", emp_FechadeSalida) :
                new ObjectParameter("emp_FechadeSalida", typeof(System.DateTime));
    
            var emp_RazonSalidaParameter = emp_RazonSalida != null ?
                new ObjectParameter("emp_RazonSalida", emp_RazonSalida) :
                new ObjectParameter("emp_RazonSalida", typeof(string));
    
            var emp_UsuarioCreaParameter = emp_UsuarioCrea.HasValue ?
                new ObjectParameter("emp_UsuarioCrea", emp_UsuarioCrea) :
                new ObjectParameter("emp_UsuarioCrea", typeof(int));
    
            var emp_FechaCreaParameter = emp_FechaCrea.HasValue ?
                new ObjectParameter("emp_FechaCrea", emp_FechaCrea) :
                new ObjectParameter("emp_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEmpleados_Insert", emp_IdentidadParameter, emp_NombresParameter, emp_ApellidosParameter, emp_FechaNacimientoParameter, emp_SexoParameter, emp_DireccionParameter, mun_IdParameter, emp_CorreoElectronicoParameter, emp_TelefonoParameter, carg_IdParameter, emp_FechaIngresoParameter, emp_FechadeSalidaParameter, emp_RazonSalidaParameter, emp_UsuarioCreaParameter, emp_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEmpleados_Update(Nullable<int> emp_Id, string emp_Identidad, string emp_Nombres, string emp_Apellidos, Nullable<System.DateTime> emp_FechaNacimiento, string emp_Sexo, string emp_Direccion, string mun_Id, string emp_CorreoElectronico, string emp_Telefono, Nullable<int> carg_Id, Nullable<System.DateTime> emp_FechaIngreso, Nullable<System.DateTime> emp_FechadeSalida, string emp_RazonSalida, Nullable<int> emp_UsuarioCrea, Nullable<System.DateTime> emp_FechaCrea, Nullable<int> emp_UsuarioModifica, Nullable<System.DateTime> emp_FechaModifica)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var emp_IdentidadParameter = emp_Identidad != null ?
                new ObjectParameter("emp_Identidad", emp_Identidad) :
                new ObjectParameter("emp_Identidad", typeof(string));
    
            var emp_NombresParameter = emp_Nombres != null ?
                new ObjectParameter("emp_Nombres", emp_Nombres) :
                new ObjectParameter("emp_Nombres", typeof(string));
    
            var emp_ApellidosParameter = emp_Apellidos != null ?
                new ObjectParameter("emp_Apellidos", emp_Apellidos) :
                new ObjectParameter("emp_Apellidos", typeof(string));
    
            var emp_FechaNacimientoParameter = emp_FechaNacimiento.HasValue ?
                new ObjectParameter("emp_FechaNacimiento", emp_FechaNacimiento) :
                new ObjectParameter("emp_FechaNacimiento", typeof(System.DateTime));
    
            var emp_SexoParameter = emp_Sexo != null ?
                new ObjectParameter("emp_Sexo", emp_Sexo) :
                new ObjectParameter("emp_Sexo", typeof(string));
    
            var emp_DireccionParameter = emp_Direccion != null ?
                new ObjectParameter("emp_Direccion", emp_Direccion) :
                new ObjectParameter("emp_Direccion", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var emp_CorreoElectronicoParameter = emp_CorreoElectronico != null ?
                new ObjectParameter("emp_CorreoElectronico", emp_CorreoElectronico) :
                new ObjectParameter("emp_CorreoElectronico", typeof(string));
    
            var emp_TelefonoParameter = emp_Telefono != null ?
                new ObjectParameter("emp_Telefono", emp_Telefono) :
                new ObjectParameter("emp_Telefono", typeof(string));
    
            var carg_IdParameter = carg_Id.HasValue ?
                new ObjectParameter("carg_Id", carg_Id) :
                new ObjectParameter("carg_Id", typeof(int));
    
            var emp_FechaIngresoParameter = emp_FechaIngreso.HasValue ?
                new ObjectParameter("emp_FechaIngreso", emp_FechaIngreso) :
                new ObjectParameter("emp_FechaIngreso", typeof(System.DateTime));
    
            var emp_FechadeSalidaParameter = emp_FechadeSalida.HasValue ?
                new ObjectParameter("emp_FechadeSalida", emp_FechadeSalida) :
                new ObjectParameter("emp_FechadeSalida", typeof(System.DateTime));
    
            var emp_RazonSalidaParameter = emp_RazonSalida != null ?
                new ObjectParameter("emp_RazonSalida", emp_RazonSalida) :
                new ObjectParameter("emp_RazonSalida", typeof(string));
    
            var emp_UsuarioCreaParameter = emp_UsuarioCrea.HasValue ?
                new ObjectParameter("emp_UsuarioCrea", emp_UsuarioCrea) :
                new ObjectParameter("emp_UsuarioCrea", typeof(int));
    
            var emp_FechaCreaParameter = emp_FechaCrea.HasValue ?
                new ObjectParameter("emp_FechaCrea", emp_FechaCrea) :
                new ObjectParameter("emp_FechaCrea", typeof(System.DateTime));
    
            var emp_UsuarioModificaParameter = emp_UsuarioModifica.HasValue ?
                new ObjectParameter("emp_UsuarioModifica", emp_UsuarioModifica) :
                new ObjectParameter("emp_UsuarioModifica", typeof(int));
    
            var emp_FechaModificaParameter = emp_FechaModifica.HasValue ?
                new ObjectParameter("emp_FechaModifica", emp_FechaModifica) :
                new ObjectParameter("emp_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEmpleados_Update", emp_IdParameter, emp_IdentidadParameter, emp_NombresParameter, emp_ApellidosParameter, emp_FechaNacimientoParameter, emp_SexoParameter, emp_DireccionParameter, mun_IdParameter, emp_CorreoElectronicoParameter, emp_TelefonoParameter, carg_IdParameter, emp_FechaIngresoParameter, emp_FechadeSalidaParameter, emp_RazonSalidaParameter, emp_UsuarioCreaParameter, emp_FechaCreaParameter, emp_UsuarioModificaParameter, emp_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEscuelas_Insert(string esc_Codigo, string esc_NombreEscuela, Nullable<int> esc_Director, Nullable<int> esc_Contacto, string esc_Telefono, string esc_Correo, string mun_Id, Nullable<int> esc_UsuarioCrea, Nullable<System.DateTime> esc_FechaCrea)
        {
            var esc_CodigoParameter = esc_Codigo != null ?
                new ObjectParameter("esc_Codigo", esc_Codigo) :
                new ObjectParameter("esc_Codigo", typeof(string));
    
            var esc_NombreEscuelaParameter = esc_NombreEscuela != null ?
                new ObjectParameter("esc_NombreEscuela", esc_NombreEscuela) :
                new ObjectParameter("esc_NombreEscuela", typeof(string));
    
            var esc_DirectorParameter = esc_Director.HasValue ?
                new ObjectParameter("esc_Director", esc_Director) :
                new ObjectParameter("esc_Director", typeof(int));
    
            var esc_ContactoParameter = esc_Contacto.HasValue ?
                new ObjectParameter("esc_Contacto", esc_Contacto) :
                new ObjectParameter("esc_Contacto", typeof(int));
    
            var esc_TelefonoParameter = esc_Telefono != null ?
                new ObjectParameter("esc_Telefono", esc_Telefono) :
                new ObjectParameter("esc_Telefono", typeof(string));
    
            var esc_CorreoParameter = esc_Correo != null ?
                new ObjectParameter("esc_Correo", esc_Correo) :
                new ObjectParameter("esc_Correo", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var esc_UsuarioCreaParameter = esc_UsuarioCrea.HasValue ?
                new ObjectParameter("esc_UsuarioCrea", esc_UsuarioCrea) :
                new ObjectParameter("esc_UsuarioCrea", typeof(int));
    
            var esc_FechaCreaParameter = esc_FechaCrea.HasValue ?
                new ObjectParameter("esc_FechaCrea", esc_FechaCrea) :
                new ObjectParameter("esc_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEscuelas_Insert", esc_CodigoParameter, esc_NombreEscuelaParameter, esc_DirectorParameter, esc_ContactoParameter, esc_TelefonoParameter, esc_CorreoParameter, mun_IdParameter, esc_UsuarioCreaParameter, esc_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEscuelas_Update(Nullable<int> esc_Id, string esc_Codigo, string esc_NombreEscuela, Nullable<int> esc_Director, Nullable<int> esc_Contacto, string esc_Telefono, string esc_Correo, string mun_Id, Nullable<int> esc_UsuarioCrea, Nullable<System.DateTime> esc_FechaCrea, Nullable<int> esc_UsuarioModifica, Nullable<System.DateTime> esc_FechaModifica)
        {
            var esc_IdParameter = esc_Id.HasValue ?
                new ObjectParameter("esc_Id", esc_Id) :
                new ObjectParameter("esc_Id", typeof(int));
    
            var esc_CodigoParameter = esc_Codigo != null ?
                new ObjectParameter("esc_Codigo", esc_Codigo) :
                new ObjectParameter("esc_Codigo", typeof(string));
    
            var esc_NombreEscuelaParameter = esc_NombreEscuela != null ?
                new ObjectParameter("esc_NombreEscuela", esc_NombreEscuela) :
                new ObjectParameter("esc_NombreEscuela", typeof(string));
    
            var esc_DirectorParameter = esc_Director.HasValue ?
                new ObjectParameter("esc_Director", esc_Director) :
                new ObjectParameter("esc_Director", typeof(int));
    
            var esc_ContactoParameter = esc_Contacto.HasValue ?
                new ObjectParameter("esc_Contacto", esc_Contacto) :
                new ObjectParameter("esc_Contacto", typeof(int));
    
            var esc_TelefonoParameter = esc_Telefono != null ?
                new ObjectParameter("esc_Telefono", esc_Telefono) :
                new ObjectParameter("esc_Telefono", typeof(string));
    
            var esc_CorreoParameter = esc_Correo != null ?
                new ObjectParameter("esc_Correo", esc_Correo) :
                new ObjectParameter("esc_Correo", typeof(string));
    
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var esc_UsuarioCreaParameter = esc_UsuarioCrea.HasValue ?
                new ObjectParameter("esc_UsuarioCrea", esc_UsuarioCrea) :
                new ObjectParameter("esc_UsuarioCrea", typeof(int));
    
            var esc_FechaCreaParameter = esc_FechaCrea.HasValue ?
                new ObjectParameter("esc_FechaCrea", esc_FechaCrea) :
                new ObjectParameter("esc_FechaCrea", typeof(System.DateTime));
    
            var esc_UsuarioModificaParameter = esc_UsuarioModifica.HasValue ?
                new ObjectParameter("esc_UsuarioModifica", esc_UsuarioModifica) :
                new ObjectParameter("esc_UsuarioModifica", typeof(int));
    
            var esc_FechaModificaParameter = esc_FechaModifica.HasValue ?
                new ObjectParameter("esc_FechaModifica", esc_FechaModifica) :
                new ObjectParameter("esc_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEscuelas_Update", esc_IdParameter, esc_CodigoParameter, esc_NombreEscuelaParameter, esc_DirectorParameter, esc_ContactoParameter, esc_TelefonoParameter, esc_CorreoParameter, mun_IdParameter, esc_UsuarioCreaParameter, esc_FechaCreaParameter, esc_UsuarioModificaParameter, esc_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbGrados_Insert(string grad_Descripcion, Nullable<int> grad_UsuarioCrea, Nullable<System.DateTime> grad_FechaCrea)
        {
            var grad_DescripcionParameter = grad_Descripcion != null ?
                new ObjectParameter("grad_Descripcion", grad_Descripcion) :
                new ObjectParameter("grad_Descripcion", typeof(string));
    
            var grad_UsuarioCreaParameter = grad_UsuarioCrea.HasValue ?
                new ObjectParameter("grad_UsuarioCrea", grad_UsuarioCrea) :
                new ObjectParameter("grad_UsuarioCrea", typeof(int));
    
            var grad_FechaCreaParameter = grad_FechaCrea.HasValue ?
                new ObjectParameter("grad_FechaCrea", grad_FechaCrea) :
                new ObjectParameter("grad_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbGrados_Insert", grad_DescripcionParameter, grad_UsuarioCreaParameter, grad_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbGrados_Update(Nullable<int> grad_Id, string grad_Descripcion, Nullable<int> grad_UsuarioCrea, Nullable<System.DateTime> grad_FechaCrea, Nullable<int> grad_UsuarioMofifica, Nullable<System.DateTime> grad_FechaModifica)
        {
            var grad_IdParameter = grad_Id.HasValue ?
                new ObjectParameter("grad_Id", grad_Id) :
                new ObjectParameter("grad_Id", typeof(int));
    
            var grad_DescripcionParameter = grad_Descripcion != null ?
                new ObjectParameter("grad_Descripcion", grad_Descripcion) :
                new ObjectParameter("grad_Descripcion", typeof(string));
    
            var grad_UsuarioCreaParameter = grad_UsuarioCrea.HasValue ?
                new ObjectParameter("grad_UsuarioCrea", grad_UsuarioCrea) :
                new ObjectParameter("grad_UsuarioCrea", typeof(int));
    
            var grad_FechaCreaParameter = grad_FechaCrea.HasValue ?
                new ObjectParameter("grad_FechaCrea", grad_FechaCrea) :
                new ObjectParameter("grad_FechaCrea", typeof(System.DateTime));
    
            var grad_UsuarioMofificaParameter = grad_UsuarioMofifica.HasValue ?
                new ObjectParameter("grad_UsuarioMofifica", grad_UsuarioMofifica) :
                new ObjectParameter("grad_UsuarioMofifica", typeof(int));
    
            var grad_FechaModificaParameter = grad_FechaModifica.HasValue ?
                new ObjectParameter("grad_FechaModifica", grad_FechaModifica) :
                new ObjectParameter("grad_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbGrados_Update", grad_IdParameter, grad_DescripcionParameter, grad_UsuarioCreaParameter, grad_FechaCreaParameter, grad_UsuarioMofificaParameter, grad_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbJornadas_Insert(string jor_Descripcion, Nullable<int> jor_UsuarioCrea, Nullable<System.DateTime> jor_FechaCrea)
        {
            var jor_DescripcionParameter = jor_Descripcion != null ?
                new ObjectParameter("jor_Descripcion", jor_Descripcion) :
                new ObjectParameter("jor_Descripcion", typeof(string));
    
            var jor_UsuarioCreaParameter = jor_UsuarioCrea.HasValue ?
                new ObjectParameter("jor_UsuarioCrea", jor_UsuarioCrea) :
                new ObjectParameter("jor_UsuarioCrea", typeof(int));
    
            var jor_FechaCreaParameter = jor_FechaCrea.HasValue ?
                new ObjectParameter("jor_FechaCrea", jor_FechaCrea) :
                new ObjectParameter("jor_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbJornadas_Insert", jor_DescripcionParameter, jor_UsuarioCreaParameter, jor_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbJornadas_Update(Nullable<int> jor_Id, string jor_Descripcion, Nullable<int> jor_UsuarioCrea, Nullable<System.DateTime> jor_FechaCrea, Nullable<int> jor_UsuarioModifica, Nullable<System.DateTime> jor_FechaModifica)
        {
            var jor_IdParameter = jor_Id.HasValue ?
                new ObjectParameter("jor_Id", jor_Id) :
                new ObjectParameter("jor_Id", typeof(int));
    
            var jor_DescripcionParameter = jor_Descripcion != null ?
                new ObjectParameter("jor_Descripcion", jor_Descripcion) :
                new ObjectParameter("jor_Descripcion", typeof(string));
    
            var jor_UsuarioCreaParameter = jor_UsuarioCrea.HasValue ?
                new ObjectParameter("jor_UsuarioCrea", jor_UsuarioCrea) :
                new ObjectParameter("jor_UsuarioCrea", typeof(int));
    
            var jor_FechaCreaParameter = jor_FechaCrea.HasValue ?
                new ObjectParameter("jor_FechaCrea", jor_FechaCrea) :
                new ObjectParameter("jor_FechaCrea", typeof(System.DateTime));
    
            var jor_UsuarioModificaParameter = jor_UsuarioModifica.HasValue ?
                new ObjectParameter("jor_UsuarioModifica", jor_UsuarioModifica) :
                new ObjectParameter("jor_UsuarioModifica", typeof(int));
    
            var jor_FechaModificaParameter = jor_FechaModifica.HasValue ?
                new ObjectParameter("jor_FechaModifica", jor_FechaModifica) :
                new ObjectParameter("jor_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbJornadas_Update", jor_IdParameter, jor_DescripcionParameter, jor_UsuarioCreaParameter, jor_FechaCreaParameter, jor_UsuarioModificaParameter, jor_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbMunicipios_Insert(string mun_Id, string mun_Descripcion, Nullable<int> mun_UsuarioCrea, Nullable<System.DateTime> mun_FechaCrea, string dep_Id)
        {
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var mun_DescripcionParameter = mun_Descripcion != null ?
                new ObjectParameter("mun_Descripcion", mun_Descripcion) :
                new ObjectParameter("mun_Descripcion", typeof(string));
    
            var mun_UsuarioCreaParameter = mun_UsuarioCrea.HasValue ?
                new ObjectParameter("mun_UsuarioCrea", mun_UsuarioCrea) :
                new ObjectParameter("mun_UsuarioCrea", typeof(int));
    
            var mun_FechaCreaParameter = mun_FechaCrea.HasValue ?
                new ObjectParameter("mun_FechaCrea", mun_FechaCrea) :
                new ObjectParameter("mun_FechaCrea", typeof(System.DateTime));
    
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbMunicipios_Insert", mun_IdParameter, mun_DescripcionParameter, mun_UsuarioCreaParameter, mun_FechaCreaParameter, dep_IdParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbMunicipios_Update(string mun_Id, string mun_Descripcion, Nullable<int> mun_UsuarioCrea, Nullable<System.DateTime> mun_FechaCrea, Nullable<int> mun_UsuarioModifica, Nullable<System.DateTime> mun_FechaModifica, string dep_Id)
        {
            var mun_IdParameter = mun_Id != null ?
                new ObjectParameter("mun_Id", mun_Id) :
                new ObjectParameter("mun_Id", typeof(string));
    
            var mun_DescripcionParameter = mun_Descripcion != null ?
                new ObjectParameter("mun_Descripcion", mun_Descripcion) :
                new ObjectParameter("mun_Descripcion", typeof(string));
    
            var mun_UsuarioCreaParameter = mun_UsuarioCrea.HasValue ?
                new ObjectParameter("mun_UsuarioCrea", mun_UsuarioCrea) :
                new ObjectParameter("mun_UsuarioCrea", typeof(int));
    
            var mun_FechaCreaParameter = mun_FechaCrea.HasValue ?
                new ObjectParameter("mun_FechaCrea", mun_FechaCrea) :
                new ObjectParameter("mun_FechaCrea", typeof(System.DateTime));
    
            var mun_UsuarioModificaParameter = mun_UsuarioModifica.HasValue ?
                new ObjectParameter("mun_UsuarioModifica", mun_UsuarioModifica) :
                new ObjectParameter("mun_UsuarioModifica", typeof(int));
    
            var mun_FechaModificaParameter = mun_FechaModifica.HasValue ?
                new ObjectParameter("mun_FechaModifica", mun_FechaModifica) :
                new ObjectParameter("mun_FechaModifica", typeof(System.DateTime));
    
            var dep_IdParameter = dep_Id != null ?
                new ObjectParameter("dep_Id", dep_Id) :
                new ObjectParameter("dep_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbMunicipios_Update", mun_IdParameter, mun_DescripcionParameter, mun_UsuarioCreaParameter, mun_FechaCreaParameter, mun_UsuarioModificaParameter, mun_FechaModificaParameter, dep_IdParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbSecciones_Insert(string sec_Descripcion, Nullable<int> sec_UsuarioCrea, Nullable<System.DateTime> sec_FechaCrea, Nullable<int> jgra_Id)
        {
            var sec_DescripcionParameter = sec_Descripcion != null ?
                new ObjectParameter("sec_Descripcion", sec_Descripcion) :
                new ObjectParameter("sec_Descripcion", typeof(string));
    
            var sec_UsuarioCreaParameter = sec_UsuarioCrea.HasValue ?
                new ObjectParameter("sec_UsuarioCrea", sec_UsuarioCrea) :
                new ObjectParameter("sec_UsuarioCrea", typeof(int));
    
            var sec_FechaCreaParameter = sec_FechaCrea.HasValue ?
                new ObjectParameter("sec_FechaCrea", sec_FechaCrea) :
                new ObjectParameter("sec_FechaCrea", typeof(System.DateTime));
    
            var jgra_IdParameter = jgra_Id.HasValue ?
                new ObjectParameter("jgra_Id", jgra_Id) :
                new ObjectParameter("jgra_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbSecciones_Insert", sec_DescripcionParameter, sec_UsuarioCreaParameter, sec_FechaCreaParameter, jgra_IdParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbSecciones_Update(Nullable<int> sec_Id, string sec_Descripcion, Nullable<int> sec_UsuarioCrea, Nullable<System.DateTime> sec_FechaCrea, Nullable<int> sec_UsuarioModifica, Nullable<System.DateTime> sec_FechaModifica, Nullable<int> jgra_Id)
        {
            var sec_IdParameter = sec_Id.HasValue ?
                new ObjectParameter("sec_Id", sec_Id) :
                new ObjectParameter("sec_Id", typeof(int));
    
            var sec_DescripcionParameter = sec_Descripcion != null ?
                new ObjectParameter("sec_Descripcion", sec_Descripcion) :
                new ObjectParameter("sec_Descripcion", typeof(string));
    
            var sec_UsuarioCreaParameter = sec_UsuarioCrea.HasValue ?
                new ObjectParameter("sec_UsuarioCrea", sec_UsuarioCrea) :
                new ObjectParameter("sec_UsuarioCrea", typeof(int));
    
            var sec_FechaCreaParameter = sec_FechaCrea.HasValue ?
                new ObjectParameter("sec_FechaCrea", sec_FechaCrea) :
                new ObjectParameter("sec_FechaCrea", typeof(System.DateTime));
    
            var sec_UsuarioModificaParameter = sec_UsuarioModifica.HasValue ?
                new ObjectParameter("sec_UsuarioModifica", sec_UsuarioModifica) :
                new ObjectParameter("sec_UsuarioModifica", typeof(int));
    
            var sec_FechaModificaParameter = sec_FechaModifica.HasValue ?
                new ObjectParameter("sec_FechaModifica", sec_FechaModifica) :
                new ObjectParameter("sec_FechaModifica", typeof(System.DateTime));
    
            var jgra_IdParameter = jgra_Id.HasValue ?
                new ObjectParameter("jgra_Id", jgra_Id) :
                new ObjectParameter("jgra_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbSecciones_Update", sec_IdParameter, sec_DescripcionParameter, sec_UsuarioCreaParameter, sec_FechaCreaParameter, sec_UsuarioModificaParameter, sec_FechaModificaParameter, jgra_IdParameter);
        }
    }
}
