
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbAlumnos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbAlumnos()
    {

        this.tbMatriculas = new HashSet<tbMatriculas>();

    }


    public int alu_Id { get; set; }

    public string alu_Identidad { get; set; }

    public string alu_Nombres { get; set; }

    public string alu_Apellidos { get; set; }

    public string alu_Sexo { get; set; }

    public System.DateTime alu_FechaNacimiento { get; set; }

    public string alu_direccion { get; set; }

    public string mun_Id { get; set; }

    public string alu_NombresEncargado { get; set; }

    public string alu_ApellidosEncargado { get; set; }

    public string alu_TelefonoEncargado { get; set; }

    public bool alu_EsActivo { get; set; }

    public string alu_RazonInactivo { get; set; }

    public int alu_UsuarioCrea { get; set; }

    public System.DateTime alu_FechaCrea { get; set; }

    public Nullable<int> alu_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> alu_FechaModifica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    public virtual tbMunicipios tbMunicipios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbMatriculas> tbMatriculas { get; set; }

}

}
