//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAlumnos()
        {
            this.tbMatriculas = new HashSet<tbMatriculas>();
        }
    
        public int alu_Id { get; set; }
        public string alu_Identidad { get; set; }
        public string alu_Nombres { get; set; }
        public string alu_Apellidos { get; set; }
        public string alu_Sexo { get; set; }
        public System.DateTime alu_FechaNacimiento { get; set; }
        public string alu_NombresEncargado { get; set; }
        public string alu_ApellidosEncargado { get; set; }
        public string alu_TelefonoEncargado { get; set; }
        public int alu_UsuarioCrea { get; set; }
        public System.DateTime alu_FechaCrea { get; set; }
        public Nullable<int> alu_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> alu_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMatriculas> tbMatriculas { get; set; }
    }
}
