
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbCarreraAsignaturas
{

    public int carasi_Id { get; set; }

    public Nullable<int> car_Id { get; set; }

    public Nullable<int> asig_Id { get; set; }

    public int carasi_UsuarioCrea { get; set; }

    public System.DateTime carasi_FechaCrea { get; set; }

    public Nullable<int> carasi_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> carasi_FechaModifica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    public virtual tbAsignaturas tbAsignaturas { get; set; }

    public virtual tbCarreras tbCarreras { get; set; }

}

}
