//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarreraAsignaturas
    {
        public int carasi_Id { get; set; }
        public Nullable<int> car_Id { get; set; }
        public Nullable<int> asig_Id { get; set; }
        public int carasi_UsuarioCrea { get; set; }
        public System.DateTime carasi_FechaCrea { get; set; }
        public Nullable<int> carasi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> carasi_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbAsignaturas tbAsignaturas { get; set; }
        public virtual tbCarreras tbCarreras { get; set; }
    }
}
