//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleadoAsignaturas
    {
        public int empa_Id { get; set; }
        public int emp_Id { get; set; }
        public int asig_Id { get; set; }
        public int empa_UsuarioCrea { get; set; }
        public System.DateTime empa_FechaCrea { get; set; }
        public Nullable<int> empa_UsuarioModifica { get; set; }
        public Nullable<int> empa_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbAsignaturas tbAsignaturas { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
    }
}
