
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbHorarioDetalles
{

    public int hode_Id { get; set; }

    public int hro_Id { get; set; }

    public int hora_Id { get; set; }

    public int empa_Id { get; set; }

    public Nullable<int> hode_UsuarioCrea { get; set; }

    public Nullable<System.DateTime> hode_FechaCrea { get; set; }

    public Nullable<int> hode_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> hode_FechaMofica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    public virtual tbEmpleadoAsignaturas tbEmpleadoAsignaturas { get; set; }

    public virtual tbHoras tbHoras { get; set; }

    public virtual tbHorarios tbHorarios { get; set; }

}

}
