
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbHoras
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbHoras()
    {

        this.tbHorarioDetalles = new HashSet<tbHorarioDetalles>();

    }


    public int hora_Id { get; set; }

    public string hora_Descricion { get; set; }

    public int jor_Id { get; set; }

    public int hora_UsuarioCrea { get; set; }

    public System.DateTime hora_FechaCrea { get; set; }

    public Nullable<int> hora_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> hora_FechaModifica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbHorarioDetalles> tbHorarioDetalles { get; set; }

}

}
