
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbHorarios
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbHorarios()
    {

        this.tbHorarioDetalles = new HashSet<tbHorarioDetalles>();

    }


    public int hro_Id { get; set; }

    public int sec_Id { get; set; }

    public int hro_Anio { get; set; }

    public int sem_Id { get; set; }

    public Nullable<int> hro_UsuarioCrea { get; set; }

    public Nullable<System.DateTime> hro_FechaCrea { get; set; }

    public Nullable<int> hro_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> hro_FechaMofica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbHorarioDetalles> tbHorarioDetalles { get; set; }

    public virtual tbSecciones tbSecciones { get; set; }

    public virtual tbSemestres tbSemestres { get; set; }

}

}
