
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbJornadaGrados
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbJornadaGrados()
    {

        this.tbSecciones = new HashSet<tbSecciones>();

    }


    public int jgra_Id { get; set; }

    public int grad_Id { get; set; }

    public int jor_Id { get; set; }

    public int jgra_UsuarioCrea { get; set; }

    public System.DateTime jgra_FechaCrea { get; set; }

    public Nullable<int> jgra_UsuarioModifica { get; set; }

    public Nullable<System.DateTime> jgra_FechaModifica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    public virtual tbGrados tbGrados { get; set; }

    public virtual tbJornadas tbJornadas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbSecciones> tbSecciones { get; set; }

}

}
