//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagos
    {
        public int cont_Id { get; set; }
        public int mat_Id { get; set; }
        public int cont_NumeroRecibo { get; set; }
        public System.DateTime cont_FechaPagado { get; set; }
        public int cont_MesesCancelados { get; set; }
        public int cont_UsuarioCrea { get; set; }
        public System.DateTime cont_FechaCrea { get; set; }
        public Nullable<int> cont_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cont_FechaModifica { get; set; }
    
        public virtual tbMatriculas tbMatriculas { get; set; }
    }
}
