
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tbSemestres
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbSemestres()
    {

        this.tbHorarios = new HashSet<tbHorarios>();

    }


    public int sem_Id { get; set; }

    public string sem_Descripcion { get; set; }

    public int sem_UsuarioCrea { get; set; }

    public System.DateTime sem_FechaCrea { get; set; }

    public Nullable<int> sem_UsuarioModfica { get; set; }

    public Nullable<System.DateTime> sem_FechaModifica { get; set; }



    public virtual tbUsuarios tbUsuarios { get; set; }

    public virtual tbUsuarios tbUsuarios1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbHorarios> tbHorarios { get; set; }

}

}
